import os
units = os.listdir(os.curdir)
units.sort()
units.remove('main.py')
units.remove('.upm')
units.remove('.git')
print("U.No\t:","\tUnit")
print("-------------------------------------------")
for i in range(len(units)):
    print(i+1,"\t\t:\t",units[i])
print("-------------------------------------------")
unitnumber = int(input("Enter unit number:"))
os.chdir(units[unitnumber-1])
files = os.listdir(os.curdir)
print("E.No\t:","\tExample")
print("-------------------------------------------")
for i in range(len(files)):
    print(i+1,"\t\t:\t",files[i])
print("-------------------------------------------")
fileno = int(input("Enter Example number to run:"))
print("-------------------------------------------")
print(files[fileno-1])
print("-------------------------------------------\n")
os.system("python "+files[fileno-1])
